### ISSUE TITLE
Permission denied error creating chaincode peer on ibmblockchain docker image - when used with composer

### ISSUE THREAD

**Issue by likepunk** [IBM-Blockchain/docker-images#5]
Hello,

I converted sample network docker images from 'hyperledger' to 'ibmblockchain', then having an issue creating peer chaincode container.

Is this a known issue? I am running HLFV11 and composer version 0.19.4 on x86...(latest docker ce 18.03.1)

I get same error either through CLI or composer-playground....it works perfectly with Hyperledger docker images.

yongkook$ **composer network start --networkName digitalproperty-network --networkVersion 0.2.3 --card PeerAdmin@hlfv1 -A admin -S adminpw -l INFO**

Starting business network digitalproperty-network at version 0.2.3

Processing these Network Admins:
userName: admin

✖ Starting business network definition. This may take a minute...

> 
> Error: Error trying to start business network. Error: No valid responses from any peers.
> Response from attempted peer comms was an error: Error: 2 UNKNOWN: error starting container: Post http://unix.sock/containers/create?name=dev-peer0.org1.example.com-digitalproperty-network-0.2.3: dial unix /host/var/run/docker.sock: connect: permission denied
> Command failed

Yongkook-Kims-MacBook-Pro:digitalproperty-app yongkook$ composer --version
v0.19.4

**Comment by likepunk** [comment]
Is there any reason you kept 'docker-entrypoint.sh ' in the root directory of the images, while hyperledger docker images don't have them? What does it do for fabric users?

Thanks,
Alex

**Comment by dhyey20** [comment]
Being discussed here: https://github.com/IBM-Blockchain/ibm-blockchain-issues/issues/125
